name: Lint diff

on:
  pull_request:
    branches:
      - master

jobs:

  diff:

    runs-on: windows-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: pip install -U flake8
    - name: Lint
      run: |
        git diff -U0 origin/main...HEAD -- addon/. > flake8.diff
        type flake8.diff | flake8 --diff --output-file=flake8.txt --tee
    - name: Comment on PR
      uses: actions/github-script@v3
      if: failure()
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'This PR introduces flake8 errors'
          })
          